services:
  sui-dev:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - sui-config:/root/.sui
      - ../:/workspace/builder-scaffold
      - ../../world-contracts:/workspace/world-contracts

volumes:
  sui-config:
